### ISSUE TITLE
Not compatible with using plymouth-encrypt

### ISSUE THREAD

**Issue by loewexy** [grazzolini/mkinitcpio-utils#3]
I tried to setup the encryptssh hook from mkinitcpio-utils in conjunction with the plymouth-encrypt hook for a nicer ui. This fails for me, because the encryptssh hook complains an already existing cryptodevice if the password is first entered in the plymouth-encrypt. This leads to a situation where the continuing boot is prevented. Is there any possibility to fix this issue?

**Comment by grazzolini** [comment]
Hi there, @loewexy. The encryptssh hook is meant to replace the encrypt hook, which is provided with the mkinitcpio package. It is based on that hook, with some modifications to allow for remote unlock. Specially, it does add a check for the case where the device is unlocked remotely, or it is unlocked physically.

I don't see why the plymouth-encrypt hook couldn't be modified to permit remote unlock. Unfortunately, I can't do this modification at this moment. If you come up with something we can include it as another hook for mkinitcpio-utils.

**Comment by loewexy** [comment]
Currently I am not very familiar with the hook concept and how they work. But I try to get into it, it should be a manageable task.

**Comment by grazzolini** [comment]
@loewexy
You can learn the differences between the hooks by comparing /usr/lib/initcpio/install/encrypt and /usr/lib/initcpio/install/encryptssh. And also the run hooks, /usr/lib/initcpio/hooks/encrypt and /usr/lib/initcpio/hooks/encryptssh.

The differences between those are a good starting point for learning how the unlock via ssh works. Since plymouth install to those directories also, you can compare all three. I'll take a look into it, if I manage to come up with some time.

**Comment by loewexy** [comment]
The comparison was very helpful, I managed to get it working and submitted pull request #4 to add the compatibility.
The AUR Package needs some modification to include the 3 new files.

**Comment by Glich440** [comment]
Was this ever implemented?

**Comment by jacklul** [comment]
This should be directly implemented in the `encryptssh` hook as `plymouth ask-for-password` call is present in base `encrypt` hook.
Since it was mentioned that `encryptssh` is based on it it should not downgrade the functionality

https://github.com/archlinux/mkinitcpio/blob/master/hooks/encrypt#L104
https://github.com/grazzolini/mkinitcpio-utils/blob/master/initcpio/hooks/encryptssh#L89
