### ISSUE TITLE
Unable to find PARTUUID for root

### ISSUE THREAD

**Issue by SquidUlysses** [grazzolini/mkinitcpio-utils#6]
I'm not certain why the _encryptssh_ hook is causing difficulties for me.  I'm following the guide on the [Arch Linux wiki](https://wiki.archlinux.org/index.php/Dm-crypt/Specialties#Remote_unlocking_.28hooks:_netconf.2C_dropbear.2C_tinyssh.2C_ppp.29) and everything seemed to go smoothly.  After rebooting I face two problems: (1) the keyboard is non-responsive on the physical terminal, so I can't type in the decryption password manually; and (2) I am able to ssh into the server running dropbear using the pre-supplied rsa key but get kicked out immediately after, again not allowing me to decrypt the drive.

From the client ssh terminal I get the following error message:
`Device PARTUUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx doesn't exist or access denied.`

The physical terminal monitor shows that I'm indeed logging in and says something like
`login from <my internal ip> with key fingerprint <my fingerprint>`

So I'm pretty sure netconf and dropbear are working.  It's _encryptssh_ specifically that's giving me trouble.  I'm at a a loss here because the errors are unexpected.  I copied the mkinitcpio.conf file from an existing conf file which has the standard _encrypt_ hook, which works fine.  So I'm pretty sure the _PARTUUID_ is correct.  The bootloader options are:

`title 		Arch Linux`
`linux 		/vmlinuz-linux`
`initrd 		/initramfs-linux.img`
`options 	ip=dhcp cryptdevice=PARTUUID=xxx...xxxx:eroot root=/dev/mapper/eroot rw`

**Something is preventing encryptssh from seeing my drive** and I can't figure out why.

**Comment by grazzolini** [comment]
Hi there,

    The error you're getting is being thrown by cryptsetup, not encryptssh itself. Even though mkinitcpio can use PARTUUID as an identifier, there is an absolute need for you to use PARTUUID?  All my setups use UUID and I've never had any issues.

    Both encrypt and encryptssh uses the function resolve_device from initcpio so, in theory, you shouldn't see a difference. I'll do some tests today using PARTUUID, so see if I can find the issue.

**Comment by grazzolini** [comment]
I did some tests and I found the issue. The encryptssh hook writes to some temporary files the name of the cryptdevice you're passing in your cmdline. This is done **before** the actual resolve_device is called. It works when you pass UUID because cryptsetup accepts it as a parameter, as is specified on it's man page.

But, cryptsetup does not accept PARTUUID as a parameter for the device, and this is what is causing the issue. I couldn't reproduce your keyboard issue though, I can type the passphrase just fine using the encryptssh hook. It doesn't work just over ssh, because the cryptsetup_shell uses the not (yet) resolved device name.

**Comment by SquidUlysses** [comment]
At some point something led me to believe that PARTUUID was required because UUID wouldn't work with some part of the (de)cryption process.  The evidence here is the opposite, though.  This fix worked, **thank you.**  I may add a note in the wiki about this.

**Comment by grazzolini** [comment]
The resolve_device function uses plain device names, as /dev/XXX, instead of /dev/disk/by-<uuid, label, partuuid>. Now that I changed it to use the resolved device name, it will work with any device that function supports. It supports UUID, PARTUUID, LABEL and PARTLABEL, on top of normal device naming.
